spring:
  webflux:
    base-path: /crypto-wallet/api
  r2dbc:
    url: r2dbc:mysql://localhost:3306/crypto-wallet
    username: root
    password: rootroot

server:
  port: 8080

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "health,metrics,loggers,refresh,info"